Master Thesis: sensorfusion/MadgwickAHRS.c File Reference
MadgwickAHRS.c File Reference
Sensor fusion.
#include "MadgwickAHRS.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
Macros
#define sampleFreq 51.136f
#define M_PI 3.14159265358979323846
Functions
float invSqrt (float x)
void MadgwickAHRSupdate (float gx, float gy, float gz, float ax, float ay, float az, float mx, float my, float mz)
Madgwick algorithm.
void MadgwickAHRSupdateIMU (float gx, float gy, float gz, float ax, float ay, float az)
Madgwick algorithm.
void QuaternionsToEulerAngles (float *euler_angles)
Convert quaternions to euler angles.
Variables
volatile float q0 = 1.0f
volatile float q1 = 0.0f
volatile float q2 = 0.0f
volatile float q3 = 0.0f
volatile float yaw =0.0f
volatile float pitch =0.0f
volatile float roll =0.0f
Detailed Description
Sensor fusion.
Version
1.0
Author
Jona Cappelle
Definition in file MadgwickAHRS.c.
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition of PI
Definition at line 39 of file MadgwickAHRS.c.
sampleFreq
#define sampleFreq 51.136f
sample frequency in Hz
Definition at line 35 of file MadgwickAHRS.c.
Function Documentation
invSqrt()
float invSqrt (float x)
Calculate inverse sqrt
Definition at line 289 of file MadgwickAHRS.c.
{
     float halfx = 0.5f * x;
     float y = x;
     long i = *(long*)&y;
     i = 0x5f3759df - (i>>1);
     y = *(float*)&i;
     y = y * (1.5f - (halfx * y * y));
     return y;
 }
Referenced by MadgwickAHRSupdate(), and MadgwickAHRSupdateIMU().
MadgwickAHRSupdate()
void MadgwickAHRSupdate (float gx, float gy, float gz, float ax, float ay, float az, float mx, float my, float mz)
Madgwick algorithm.
9 DoF sensor fusion
Note
Gyro + Accel + Magn fusion
Parameters
[in] gx Gyro x
[in] gy Gyro y
[in] gz Gyro a
[in] ax Accel x
[in] ay Accel y
[in] az Accel a
[in] mx Magn x
[in] my Magn y
[in] mz Magn a
Definition at line 92 of file MadgwickAHRS.c.
{
     float recipNorm;
     float s0, s1, s2, s3;
     float qDot1, qDot2, qDot3, qDot4;
     float hx, hy;
     float _2q0mx, _2q0my, _2q0mz, _2q1mx, _2bx, _2bz, _4bx, _4bz, _2q0, _2q1, _2q2, _2q3, _2q0q2, _2q2q3, q0q0, q0q1, q0q2, q0q3, q1q1, q1q2, q1q3, q2q2, q2q3, q3q3;
     // Use IMU algorithm if magnetometer measurement invalid (avoids NaN in magnetometer normalisation)
     if((mx == 0.0f) && (my == 0.0f) && (mz == 0.0f)) {
         MadgwickAHRSupdateIMU(gx, gy, gz, ax, ay, az);
         return;
     }
     // Rate of change of quaternion from gyroscope
     qDot1 = 0.5f * (-q1 * gx - q2 * gy - q3 * gz);
     qDot2 = 0.5f * (q0 * gx + q2 * gz - q3 * gy);
     qDot3 = 0.5f * (q0 * gy - q1 * gz + q3 * gx);
     qDot4 = 0.5f * (q0 * gz + q1 * gy - q2 * gx);
     // Compute feedback only if accelerometer measurement valid (avoids NaN in accelerometer normalisation)
     if(!((ax == 0.0f) && (ay == 0.0f) && (az == 0.0f))) {
         // Normalise accelerometer measurement
         recipNorm = invSqrt(ax * ax + ay * ay + az * az);
         ax *= recipNorm;
         ay *= recipNorm;
         az *= recipNorm;
         // Normalise magnetometer measurement
         recipNorm = invSqrt(mx * mx + my * my + mz * mz);
         mx *= recipNorm;
         my *= recipNorm;
         mz *= recipNorm;
         // Auxiliary variables to avoid repeated arithmetic
         _2q0mx = 2.0f * q0 * mx;
         _2q0my = 2.0f * q0 * my;
         _2q0mz = 2.0f * q0 * mz;
         _2q1mx = 2.0f * q1 * mx;
         _2q0 = 2.0f * q0;
         _2q1 = 2.0f * q1;
         _2q2 = 2.0f * q2;
         _2q3 = 2.0f * q3;
         _2q0q2 = 2.0f * q0 * q2;
         _2q2q3 = 2.0f * q2 * q3;
         q0q0 = q0 * q0;
         q0q1 = q0 * q1;
         q0q2 = q0 * q2;
         q0q3 = q0 * q3;
         q1q1 = q1 * q1;
         q1q2 = q1 * q2;
         q1q3 = q1 * q3;
         q2q2 = q2 * q2;
         q2q3 = q2 * q3;
         q3q3 = q3 * q3;
         // Reference direction of Earth's magnetic field
         hx = mx * q0q0 - _2q0my * q3 + _2q0mz * q2 + mx * q1q1 + _2q1 * my * q2 + _2q1 * mz * q3 - mx * q2q2 - mx * q3q3;
         hy = _2q0mx * q3 + my * q0q0 - _2q0mz * q1 + _2q1mx * q2 - my * q1q1 + my * q2q2 + _2q2 * mz * q3 - my * q3q3;
         _2bx = sqrt(hx * hx + hy * hy);
         _2bz = -_2q0mx * q2 + _2q0my * q1 + mz * q0q0 + _2q1mx * q3 - mz * q1q1 + _2q2 * my * q3 - mz * q2q2 + mz * q3q3;
         _4bx = 2.0f * _2bx;
         _4bz = 2.0f * _2bz;
         // Gradient decent algorithm corrective step
         s0 = -_2q2 * (2.0f * q1q3 - _2q0q2 - ax) + _2q1 * (2.0f * q0q1 + _2q2q3 - ay) - _2bz * q2 * (_2bx * (0.5f - q2q2 - q3q3) + _2bz * (q1q3 - q0q2) - mx) + (-_2bx * q3 + _2bz * q1) * (_2bx * (q1q2 - q0q3) + _2bz * (q0q1 + q2q3) - my) + _2bx * q2 * (_2bx * (q0q2 + q1q3) + _2bz * (0.5f - q1q1 - q2q2) - mz);
         s1 = _2q3 * (2.0f * q1q3 - _2q0q2 - ax) + _2q0 * (2.0f * q0q1 + _2q2q3 - ay) - 4.0f * q1 * (1 - 2.0f * q1q1 - 2.0f * q2q2 - az) + _2bz * q3 * (_2bx * (0.5f - q2q2 - q3q3) + _2bz * (q1q3 - q0q2) - mx) + (_2bx * q2 + _2bz * q0) * (_2bx * (q1q2 - q0q3) + _2bz * (q0q1 + q2q3) - my) + (_2bx * q3 - _4bz * q1) * (_2bx * (q0q2 + q1q3) + _2bz * (0.5f - q1q1 - q2q2) - mz);
         s2 = -_2q0 * (2.0f * q1q3 - _2q0q2 - ax) + _2q3 * (2.0f * q0q1 + _2q2q3 - ay) - 4.0f * q2 * (1 - 2.0f * q1q1 - 2.0f * q2q2 - az) + (-_4bx * q2 - _2bz * q0) * (_2bx * (0.5f - q2q2 - q3q3) + _2bz * (q1q3 - q0q2) - mx) + (_2bx * q1 + _2bz * q3) * (_2bx * (q1q2 - q0q3) + _2bz * (q0q1 + q2q3) - my) + (_2bx * q0 - _4bz * q2) * (_2bx * (q0q2 + q1q3) + _2bz * (0.5f - q1q1 - q2q2) - mz);
         s3 = _2q1 * (2.0f * q1q3 - _2q0q2 - ax) + _2q2 * (2.0f * q0q1 + _2q2q3 - ay) + (-_4bx * q3 + _2bz * q1) * (_2bx * (0.5f - q2q2 - q3q3) + _2bz * (q1q3 - q0q2) - mx) + (-_2bx * q0 + _2bz * q2) * (_2bx * (q1q2 - q0q3) + _2bz * (q0q1 + q2q3) - my) + _2bx * q1 * (_2bx * (q0q2 + q1q3) + _2bz * (0.5f - q1q1 - q2q2) - mz);
         recipNorm = invSqrt(s0 * s0 + s1 * s1 + s2 * s2 + s3 * s3); // normalise step magnitude
         s0 *= recipNorm;
         s1 *= recipNorm;
         s2 *= recipNorm;
         s3 *= recipNorm;
         // Apply feedback step
         qDot1 -= beta * s0;
         qDot2 -= beta * s1;
         qDot3 -= beta * s2;
         qDot4 -= beta * s3;
     }
     // Integrate rate of change of quaternion to yield quaternion
     q0 += qDot1 * (1.0f / sampleFreq);
     q1 += qDot2 * (1.0f / sampleFreq);
     q2 += qDot3 * (1.0f / sampleFreq);
     q3 += qDot4 * (1.0f / sampleFreq);
     // Normalise quaternion
     recipNorm = invSqrt(q0 * q0 + q1 * q1 + q2 * q2 + q3 * q3);
     q0 *= recipNorm;
     q1 *= recipNorm;
     q2 *= recipNorm;
     q3 *= recipNorm;
 }
References beta, invSqrt(), MadgwickAHRSupdateIMU(), q0, q1, q2, q3, and sampleFreq.
Referenced by measure_send().
MadgwickAHRSupdateIMU()
void MadgwickAHRSupdateIMU (float gx, float gy, float gz, float ax, float ay, float az)
Madgwick algorithm.
6 DoF sensor fusion
Note
Gyro + Accel fusion
Parameters
[in] gx Gyro x
[in] gy Gyro y
[in] gz Gyro a
[in] ax Accel x
[in] ay Accel y
[in] az Accel a
Definition at line 217 of file MadgwickAHRS.c.
{
     float recipNorm;
     float s0, s1, s2, s3;
     float qDot1, qDot2, qDot3, qDot4;
     float _2q0, _2q1, _2q2, _2q3, _4q0, _4q1, _4q2 ,_8q1, _8q2, q0q0, q1q1, q2q2, q3q3;
     // Rate of change of quaternion from gyroscope
     qDot1 = 0.5f * (-q1 * gx - q2 * gy - q3 * gz);
     qDot2 = 0.5f * (q0 * gx + q2 * gz - q3 * gy);
     qDot3 = 0.5f * (q0 * gy - q1 * gz + q3 * gx);
     qDot4 = 0.5f * (q0 * gz + q1 * gy - q2 * gx);
     // Compute feedback only if accelerometer measurement valid (avoids NaN in accelerometer normalisation)
     if(!((ax == 0.0f) && (ay == 0.0f) && (az == 0.0f))) {
         // Normalise accelerometer measurement
         recipNorm = invSqrt(ax * ax + ay * ay + az * az);
         ax *= recipNorm;
         ay *= recipNorm;
         az *= recipNorm;
         // Auxiliary variables to avoid repeated arithmetic
         _2q0 = 2.0f * q0;
         _2q1 = 2.0f * q1;
         _2q2 = 2.0f * q2;
         _2q3 = 2.0f * q3;
         _4q0 = 4.0f * q0;
         _4q1 = 4.0f * q1;
         _4q2 = 4.0f * q2;
         _8q1 = 8.0f * q1;
         _8q2 = 8.0f * q2;
         q0q0 = q0 * q0;
         q1q1 = q1 * q1;
         q2q2 = q2 * q2;
         q3q3 = q3 * q3;
         // Gradient decent algorithm corrective step
         s0 = _4q0 * q2q2 + _2q2 * ax + _4q0 * q1q1 - _2q1 * ay;
         s1 = _4q1 * q3q3 - _2q3 * ax + 4.0f * q0q0 * q1 - _2q0 * ay - _4q1 + _8q1 * q1q1 + _8q1 * q2q2 + _4q1 * az;
         s2 = 4.0f * q0q0 * q2 + _2q0 * ax + _4q2 * q3q3 - _2q3 * ay - _4q2 + _8q2 * q1q1 + _8q2 * q2q2 + _4q2 * az;
         s3 = 4.0f * q1q1 * q3 - _2q1 * ax + 4.0f * q2q2 * q3 - _2q2 * ay;
         recipNorm = invSqrt(s0 * s0 + s1 * s1 + s2 * s2 + s3 * s3); // normalise step magnitude
         s0 *= recipNorm;
         s1 *= recipNorm;
         s2 *= recipNorm;
         s3 *= recipNorm;
         // Apply feedback step
         qDot1 -= beta * s0;
         qDot2 -= beta * s1;
         qDot3 -= beta * s2;
         qDot4 -= beta * s3;
     }
     // Integrate rate of change of quaternion to yield quaternion
     q0 += qDot1 * (1.0f / sampleFreq);
     q1 += qDot2 * (1.0f / sampleFreq);
     q2 += qDot3 * (1.0f / sampleFreq);
     q3 += qDot4 * (1.0f / sampleFreq);
     // Normalise quaternion
     recipNorm = invSqrt(q0 * q0 + q1 * q1 + q2 * q2 + q3 * q3);
     q0 *= recipNorm;
     q1 *= recipNorm;
     q2 *= recipNorm;
     q3 *= recipNorm;
 }
References beta, invSqrt(), q0, q1, q2, q3, and sampleFreq.
Referenced by MadgwickAHRSupdate().
QuaternionsToEulerAngles()
void QuaternionsToEulerAngles (float * euler_angles)
Convert quaternions to euler angles.
Note
Euler angles are less accurate and suffer from Gimbal Lock
Parameters
[out] euler_angles pointer to location of euler angles storage
Definition at line 351 of file MadgwickAHRS.c.
 {
     // roll (x-axis rotation)
     double sinr_cosp = 2 * (q0 * q1 + q2 * q3);
     double cosr_cosp = 1 - 2 * (q1 * q1 + q2 * q2);
     roll = atan2(sinr_cosp, cosr_cosp);
     // pitch (y-axis rotation)
     double sinp = 2 * (q0 * q2 - q3 * q1);
     if (abs(sinp) >= 1)
         pitch = copysign(M_PI/ 2, sinp); // use 90 degrees if out of range
     else
         pitch = asin(sinp);
     // yaw (z-axis rotation)
     double siny_cosp = 2 * (q0 * q3 + q1 * q2);
     double cosy_cosp = 1 - 2 * (q2 * q2 + q3 * q3);
     yaw = atan2(siny_cosp, cosy_cosp);
 /* Pass pointers through to main file */
     euler_angles[0] = roll;
     euler_angles[1] = pitch;
     euler_angles[2] = yaw;
 }
References M_PI, pitch, q0, q1, q2, q3, roll, and yaw.
Referenced by measure_send().
Variable Documentation
pitch
volatile float pitch =0.0f
Definition at line 46 of file MadgwickAHRS.c.
Referenced by QuaternionsToEulerAngles().
q0
volatile float q0 = 1.0f
Definition at line 45 of file MadgwickAHRS.c.
Referenced by MadgwickAHRSupdate(), MadgwickAHRSupdateIMU(), and QuaternionsToEulerAngles().
q1
volatile float q1 = 0.0f
Definition at line 45 of file MadgwickAHRS.c.
Referenced by MadgwickAHRSupdate(), MadgwickAHRSupdateIMU(), and QuaternionsToEulerAngles().
q2
volatile float q2 = 0.0f
Definition at line 45 of file MadgwickAHRS.c.
Referenced by MadgwickAHRSupdate(), MadgwickAHRSupdateIMU(), and QuaternionsToEulerAngles().
q3
volatile float q3 = 0.0f
quaternion of sensor frame relative to auxiliary frame
Definition at line 45 of file MadgwickAHRS.c.
Referenced by MadgwickAHRSupdate(), MadgwickAHRSupdateIMU(), and QuaternionsToEulerAngles().
roll
volatile float roll =0.0f
Yaw, pith, roll result
Definition at line 46 of file MadgwickAHRS.c.
Referenced by QuaternionsToEulerAngles().
yaw
volatile float yaw =0.0f
Definition at line 46 of file MadgwickAHRS.c.
Referenced by QuaternionsToEulerAngles().