Master Thesis: ble/ble.c File Reference
ble.c File Reference
Send data via BLE wirelessly.
#include "ble.h"
#include "em_device.h"
#include "em_chip.h"
#include "em_cmu.h"
#include "em_emu.h"
#include "em_gpio.h"
#include "em_usart.h"
#include "em_rtc.h"
#include "em_adc.h"
#include "em_wdog.h"
#include "rtcdriver.h"
#include "em_core.h"
#include "debug_dbprint.h"
#include "delay.h"
#include "interrupt.h"
#include "adc.h"
#include "pinout.h"
#include <stdint.h>
#include <stdbool.h>
#include "uart.h"
Functions
void BLE_Init ()
BLE chip init.
void BLE_power (bool enable)
Turn power on/off for BLE module.
void BLE_rxtx_enable (bool enable)
Enable disable RX/TX pins from BLE module.
void BLE_connect ()
Connect sequence BLE.
void BLE_check_connect ()
Check if LED pin on BLE is high to check if the module is connected to a receiver.
void BLE_disconnect ()
Disconnect BLE from receiver.
void BLE_sendData4 (uint8_t data_in[])
Test function, not used.
void BLE_sendData (uint8_t *data, uint8_t *batt, uint8_t length, uint8_t *ble_data)
Send all the data over BLE.
void BLE_readData (uint8_t *readData, uint8_t length)
Test function, not used.
void BLE_sendIMUData (uint8_t *gyroData, uint8_t *accelData, uint8_t *magnData)
Test function, not used.
void float_to_uint8_t (float *input, uint8_t *out)
Float to uint8_t conversion.
void float_to_uint8_t_x3 (float *in, uint8_t *out)
Float to uint8_t conversion x3.
void BLE_set_output_power (uint8_t power)
Set BLE output power.
Variables
bool ble_Initialized = false
bool check = false
uint8_t buffer [80]
uint8_t BLE_POWER_ON_RETURN [7] = { 0x02, 0x41, 0x02, 0x00, 0x01, 0x01, 0x41 }
bool bleConnected
Detailed Description
Send data via BLE wirelessly.
Version
1.0
Author
Jona Cappelle
Definition in file ble.c.
Function Documentation
BLE_check_connect()
void BLE_check_connect ()
Check if LED pin on BLE is high to check if the module is connected to a receiver.
Note
There is some delay on the actual connection and the pin turning high
Definition at line 179 of file ble.c.
 {
     bleConnected = GPIO_PinInGet(BLE_LED2_PORT, BLE_LED2_PIN);
 }
References BLE_LED2_PIN, BLE_LED2_PORT, and bleConnected.
Referenced by measure_send().
BLE_connect()
void BLE_connect ()
Connect sequence BLE.
The only function that's not send interrupt based (can be a future improvement)
Definition at line 152 of file ble.c.
 {
 //  while(!bleConnected)
 //  {
         /* Check if BLE is connected to device */
 //      BLE_check_connect();
         //Connect A -> B
         const char connect[] = { 0x02, 0x06, 0x06, 0x00, 0xBB, 0x04, 0x20, 0xDA, 0x18, 0x00, 0x5F };
         for (int i=0 ; i < sizeof(connect) ; i++ )
         {
           USART_Tx(USART1, connect[i]);
         }
 //  }
 }
Referenced by measure_send().
BLE_disconnect()
void BLE_disconnect ()
Disconnect BLE from receiver.
Note
takes approx 1sec
Definition at line 195 of file ble.c.
 {
       //Disconnect A -> B
       const char disconnect[] = { 0x02, 0x07, 0x00, 0x00, 0x05 };
       for (int i=0 ; i < sizeof(disconnect) ; i++ )
       {
           USART_Tx(USART1, disconnect[i]);
       }
 }
BLE_Init()
void BLE_Init ()
BLE chip init.
Init UART Init BLE power pin
Definition at line 61 of file ble.c.
 {
     uart_Init();
     /* Set pinmode for reading BLE LED 2 state */
     GPIO_PinModeSet(BLE_LED2_PORT, BLE_LED2_PIN, gpioModeInputPullFilter, 0);
 }
References BLE_LED2_PIN, BLE_LED2_PORT, and uart_Init().
BLE_power()
void BLE_power (bool enable)
Turn power on/off for BLE module.
Note
Extra 30 µF capacitor needed on VDD line to prevent too much voltage drop
Parameters
[in] enable
'true' - BLE on
'false' - BLE off
Definition at line 84 of file ble.c.
 {
     /* Initialize VDD pin if not already the case */
 //  if (!ble_Initialized)
 //  {
 //      /* In the case of gpioModePushPull", the last argument directly sets the pin state */
 //      GPIO_PinModeSet(BLE_POWER_PORT, BLE_POWER_PIN, gpioModePushPull, enable);
         /* Check if the right sequence is returned */
 //      BLE_readData( buffer, BUFFER_SIZE );
 //
 //      check = Check_Equal(buffer, BLE_POWER_ON_RETURN, 7);
 //      if ( check != true )
 //      {
 //          return BLE_ERROR;
 //      }
 //      ble_Initialized = true;
 //  }
 //  else
 //  {
         if (enable) GPIO_PinModeSet(BLE_POWER_PORT, BLE_POWER_PIN, gpioModePushPull, 1); /* Enable VDD pin */
         else {
             GPIO_PinModeSet(BLE_POWER_PORT, BLE_POWER_PIN, gpioModeDisabled, 0); /* Disable VDD pin */
         }
 //  }
 //  return 0;
 }
References BLE_POWER_PIN, and BLE_POWER_PORT.
Referenced by measure_send().
BLE_readData()
void BLE_readData (uint8_t * readData, uint8_t length)
Test function, not used.
Definition at line 316 of file ble.c.
 {
 //    while (1)
 //    {
 //      // Read a line from the UART
 //      for (int i = 0; i < BUFFER_SIZE - 1 ; i++ )
 //      {
 //        RX_buffer[i] = USART_Rx(USART1);
 //        if (RX_buffer[i] == '\r')
 //        {
 //          break; // Breaking on CR prevents it from being counted in the number of bytes
 //        }
 //      }
 //    }
     uartGetData( readData, length );
 }
References uartGetData().
BLE_rxtx_enable()
void BLE_rxtx_enable (bool enable)
Enable disable RX/TX pins from BLE module.
Note
Disable when going to sleep, can otherwise draw some unwanted power
Parameters
[in] enable
'true' - enable
'false' - disable
Definition at line 128 of file ble.c.
 {
     if(enable)
     {
           GPIO_PinModeSet(BLE_PORT, BLE_PIN_RX, gpioModeInput, 0);
           GPIO_PinModeSet(BLE_PORT, BLE_PIN_TX, gpioModePushPull, 1);
     }else{
         /* In ACTION_SLEEP mode the UART is disabled, so the module will not receive or transmit any
 data. To prevent leakage current, the host shall not pull the UART_RX to LOW level (as the
 module has an internal pull-up resistor enabled on this pin).*/
         GPIO_PinModeSet(BLE_PORT, BLE_PIN_RX, gpioModeDisabled, 0);
         GPIO_PinModeSet(BLE_PORT, BLE_PIN_TX, gpioModeDisabled, 0);
     }
 }
References BLE_PIN_RX, BLE_PIN_TX, and BLE_PORT.
BLE_sendData()
void BLE_sendData (uint8_t * data, uint8_t * batt, uint8_t length, uint8_t * ble_data)
Send all the data over BLE.
xxx
Note
xxx
Warning
xxx
Parameters
[in] data Euler angles
[in] length packet length
[in] batt battery in percentage
[out] ble_data return ble_data for debugging purposes
Definition at line 269 of file ble.c.
 {
     int ble_packet_length = length + 5;
     // uint8_t ble_data[ble_packet_length];
     int d = 0;
     ble_data[0] = 0x02;
     ble_data[1] = 0x04;
     ble_data[2] = length;
     ble_data[3] = 0x00;
     while ( d < length)
     {
         ble_data[4+d] = data[d];
         d++;
     }
     ble_data[ble_packet_length-2] = batt[0];
     //calculate Checksum CS
     uint8_t checksum = 0x00;
     for (int j=0;j<(ble_packet_length-1);j++)
     {
         checksum = checksum^ble_data[j];
     }
     ble_data[ble_packet_length-1] = checksum;
     //Send data out
 //  for (int i = 0; i < ble_packet_length; i++)
 //  {
 //        USART_Tx(USART1, ble_data[i]);
 //  }
     /* Send data interrupt driven */
     uartPutData( ble_data, ble_packet_length );
 }
References data, and uartPutData().
Referenced by measure_send().
BLE_sendData4()
void BLE_sendData4 (uint8_t data_in[])
Test function, not used.
Definition at line 212 of file ble.c.
 {
     int d=0;
     //Preface
     /* Start signal - command - length - payload - checksum */
     uint8_t data[9] = {0x02, 0x04, 0x04, 0x00 };
     //concatenate
     while (d < (4))
       {
           data[4+d] = data_in[d];
           d++;
       }
     //calculate Checksum CS
     uint8_t checksum = 0x00;
     for (int j=0;j<(sizeof(data)/sizeof(uint8_t));j++)
     {
         checksum = checksum^data[j];
     }
     data[8] = checksum;
     //Send data out
     for (int i = 0; i < 9; i++)
     {
           USART_Tx(USART1, data[i]);
     }
 }
References data.
BLE_sendIMUData()
void BLE_sendIMUData (uint8_t * gyroData, uint8_t * accelData, uint8_t * magnData)
Test function, not used.
Definition at line 342 of file ble.c.
 {
     int d=0;
     //Preface
     /* Start signal - command - length - payload - checksum */
     char data[23] = { 0x02, 0x04, 0x06, 0x00 };
     //concatenate
     while (d < 6)
       {
           data[4+d] = gyroData[d];
           d++;
       }
     d=0;
     while (d < 6)
     {
         data[10+d] = accelData[d];
         d++;
     }
     d=0;
     while (d < 6)
     {
         data[16+d] = magnData[d];
         d++;
     }
     //calculate Checksum CS
     char checksum = 0x00;
     for (int j=0;j<(sizeof(data)/sizeof(char));j++)
     {
         checksum = checksum^data[j];
     }
     data[22] = checksum;
     //Send data out
     for (int i = 0; i < 23; i++) //i runs until length of char data[]
     {
           USART_Tx(USART1, data[i]);
     }
 }
References data.
BLE_set_output_power()
void BLE_set_output_power (uint8_t power)
Set BLE output power.
Momentarily not used, since the reset value of the BLE is the one used
Note
xxx
Warning
xxx
Parameters
[in] power power value (see datasheet for options)
Definition at line 454 of file ble.c.
 {
         int len = 7;
         uint8_t data[7];
         data[0] = 0x02;
         data[1] = 0x11;
         data[2] = 0x02;
         data[3] = 0x00;
         data[4] = 0x11;
         data[5] = power;
         //calculate Checksum CS
         uint8_t checksum = 0x00;
         for (int j=0;j<(7-1);j++)
         {
             checksum = checksum^data[j];
         }
         data[len-1] = checksum;
         uartPutData( data, len );
 }
References data, and uartPutData().
float_to_uint8_t()
void float_to_uint8_t (float * input, uint8_t * out)
Float to uint8_t conversion.
Parameters
[in] input float
[out] out 4 x uint8_t's
Definition at line 399 of file ble.c.
 {
     union{
         float in;
         uint8_t bytes[sizeof(float)];
     }thing;
     thing.in = input[0];
     for( int i=0; i<sizeof(float); i++)
     {
         out[i] = thing.bytes[i];
     }
 }
Referenced by float_to_uint8_t_x3().
float_to_uint8_t_x3()
void float_to_uint8_t_x3 (float * in, uint8_t * out)
Float to uint8_t conversion x3.
Parameters
[in] input float
[out] out 4 x uint8_t's
Definition at line 427 of file ble.c.
 {
     float_to_uint8_t( &in[0], &out[0] );
     float_to_uint8_t( &in[1], &out[4] );
     float_to_uint8_t( &in[2], &out[8] );
 }
References float_to_uint8_t().
Referenced by measure_send().
Variable Documentation
ble_Initialized
bool ble_Initialized = false
Definition at line 42 of file ble.c.
BLE_POWER_ON_RETURN
uint8_t BLE_POWER_ON_RETURN[7] = { 0x02, 0x41, 0x02, 0x00, 0x01, 0x01, 0x41 }
Definition at line 47 of file ble.c.
bleConnected
bool bleConnected
Keep track of the state of the BLE module
Definition at line 125 of file main.c.
Referenced by BLE_check_connect(), and measure_send().
buffer
uint8_t buffer[80]
Definition at line 46 of file ble.c.
check
bool check = false
Definition at line 44 of file ble.c.