Master Thesis: ble/uart.h File Reference
uart.h File Reference
#include <stdint.h>
#include <stdbool.h>
Functions
void uart_Init ()
uint8_t uartGetChar ()
void uartPutChar (uint8_t ch)
void uartPutData (uint8_t *dataPtr, uint32_t dataLen)
uint32_t uartGetData (uint8_t *dataPtr, uint32_t dataLen)
void UART1_RX_IRQHandler (void)
void UART1_TX_IRQHandler (void)
Function Documentation
UART1_RX_IRQHandler()
void UART1_RX_IRQHandler (void)
UART1_TX_IRQHandler()
void UART1_TX_IRQHandler (void)
uart_Init()
void uart_Init ()
Definition at line 41 of file uart.c.
 {
     // Enable oscillator to GPIO and USART1 modules
     CMU_ClockEnable(cmuClock_HFPER, true);
     CMU_ClockEnable(cmuClock_GPIO, true);
     CMU_ClockEnable(cmuClock_USART1, true);
     // set pin modes for UART TX and RX pins
     GPIO_PinModeSet(BLE_PORT, BLE_PIN_RX, gpioModeInput, 0);
     GPIO_PinModeSet(BLE_PORT, BLE_PIN_TX, gpioModePushPull, 1);
     // Initialize USART asynchronous mode and route pins
     USART_InitAsync(BLE_USART, &init);
     /* Prepare UART Rx and Tx interrupts */
     USART_IntClear(BLE_USART, _USART_IFC_MASK);
     USART_IntEnable(BLE_USART, USART_IEN_RXDATAV);
     NVIC_ClearPendingIRQ(USART1_RX_IRQn);
     NVIC_ClearPendingIRQ(USART1_TX_IRQn);
     NVIC_EnableIRQ(USART1_RX_IRQn);
     NVIC_EnableIRQ(USART1_TX_IRQn);
     BLE_USART->ROUTE |= USART_ROUTE_TXPEN | USART_ROUTE_RXPEN | USART_ROUTE_LOCATION_LOC0;
       /* Enable UART */
     USART_Enable(BLE_USART, usartEnable);
 }
References BLE_PIN_RX, BLE_PIN_TX, BLE_PORT, and BLE_USART.
Referenced by BLE_Init().
uartGetChar()
uint8_t uartGetChar ()
Definition at line 77 of file uart.c.
 {
   uint8_t ch;
   /* Check if there is a byte that is ready to be fetched. If no byte is ready, wait for incoming data */
   if (rxBuf.pendingBytes < 1)
   {
     while (rxBuf.pendingBytes < 1) ;
   }
   /* Copy data from buffer */
   ch        = rxBuf.data[rxBuf.rdI];
   rxBuf.rdI = (rxBuf.rdI + 1) % BUFFERSIZE;
   /* Decrement pending byte counter */
   rxBuf.pendingBytes--;
   return ch;
References BUFFERSIZE, circularBuffer::data, circularBuffer::pendingBytes, circularBuffer::rdI, and rxBuf.
uartGetData()
uint32_t uartGetData (uint8_t * dataPtr, uint32_t dataLen)
Definition at line 165 of file uart.c.
 {
   uint32_t i = 0;
   /* Wait until the requested number of bytes are available */
   if (rxBuf.pendingBytes < dataLen)
   {
     while (rxBuf.pendingBytes < dataLen) ;
   }
   if (dataLen == 0)
   {
     dataLen = rxBuf.pendingBytes;
   }
   /* Copy data from Rx buffer to dataPtr */
   while (i < dataLen)
   {
     *(dataPtr + i) = rxBuf.data[rxBuf.rdI];
     rxBuf.rdI      = (rxBuf.rdI + 1) % BUFFERSIZE;
     i++;
   }
   /* Decrement pending byte counter */
References BUFFERSIZE, circularBuffer::data, circularBuffer::pendingBytes, circularBuffer::rdI, and rxBuf.
Referenced by BLE_readData().
uartPutChar()
void uartPutChar (uint8_t ch)
Definition at line 103 of file uart.c.
 {
   /* Check if Tx queue has room for new data */
   if ((txBuf.pendingBytes + 1) > BUFFERSIZE)
   {
     /* Wait until there is room in queue */
     while ((txBuf.pendingBytes + 1) > BUFFERSIZE) ;
   }
   /* Copy ch into txBuffer */
   txBuf.data[txBuf.wrI] = ch;
   txBuf.wrI             = (txBuf.wrI + 1) % BUFFERSIZE;
   /* Increment pending byte counter */
   txBuf.pendingBytes++;
   /* Enable interrupt on USART TX Buffer*/
References BLE_USART, BUFFERSIZE, circularBuffer::data, circularBuffer::pendingBytes, txBuf, and circularBuffer::wrI.
uartPutData()
void uartPutData (uint8_t * dataPtr, uint32_t dataLen)
Definition at line 129 of file uart.c.
 {
   uint32_t i = 0;
   /* Check if buffer is large enough for data */
   if (dataLen > BUFFERSIZE)
   {
     /* Buffer can never fit the requested amount of data */
     return;
   }
   /* Check if buffer has room for new data */
   if ((txBuf.pendingBytes + dataLen) > BUFFERSIZE)
   {
     /* Wait until room */
     while ((txBuf.pendingBytes + dataLen) > BUFFERSIZE) ;
   }
   /* Fill dataPtr[0:dataLen-1] into txBuffer */
   while (i < dataLen)
   {
     txBuf.data[txBuf.wrI] = *(dataPtr + i);
     txBuf.wrI             = (txBuf.wrI + 1) % BUFFERSIZE;
     i++;
   }
   /* Increment pending byte counter */
   txBuf.pendingBytes += dataLen;
References BLE_USART, BUFFERSIZE, circularBuffer::data, circularBuffer::pendingBytes, txBuf, and circularBuffer::wrI.
Referenced by BLE_sendData(), and BLE_set_output_power().